name: Deploy to cPanel

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use a recent, stable Node.js version
      
      - name: Validate secrets
        run: |
          if [ -z "${{ secrets.CPANEL_HOST }}" ]; then
            echo "Error: CPANEL_HOST secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.CPANEL_USER }}" ]; then
            echo "Error: CPANEL_USER secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "Error: SSH_PRIVATE_KEY secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.DEPLOY_PATH }}" ]; then
            echo "Error: DEPLOY_PATH secret is not set"
            exit 1
          fi
          echo "All required secrets are configured"
        
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.CPANEL_HOST }} >> ~/.ssh/known_hosts
          echo "SSH setup completed successfully"
          
      - name: Deploy and build on server
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }} << 'DEPLOY_EOF'
            
            echo "Starting deployment on server..."
            
            # Navigate to the deployment directory
            cd ${{ secrets.DEPLOY_PATH }}
            
            # Pull the latest changes from the Git repository
            git pull
            
            # Install PHP dependencies (using --no-dev to keep it clean)
            composer install --no-dev --optimize-autoloader
            
            # Install Node.js dependencies
            npm install
            
            # Fix permission issues that can arise with npm executables
            chmod +x node_modules/.bin/* || true
            chmod +x node_modules/@esbuild/linux-x64/bin/* || true

            # Build front-end assets with Vite
            npm run build
            
            # Run database migrations (with --force for production safety)
            php artisan migrate --force
            
            # Clear and cache application for performance
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # Set proper permissions for storage and cache directories
            chmod -R 755 storage bootstrap/cache
            chown -R ${{ secrets.CPANEL_USER }}:${{ secrets.CPANEL_USER }} storage bootstrap/cache
            
            echo "Deployment completed successfully!"
          DEPLOY_EOF